Sort and filter out duplicate certs, add file check
Sort certs and filter out duplicate certificate files, check for certificate file existence

diff --git a/nginx-certwatch b/nginx-certwatch
--- a/nginx-certwatch
+++ b/nginx-certwatch
@@ -109,6 +109,16 @@ if ! command -v awk > /dev/null 2>&1 ; then
 	exit 1
 fi
 
+if ! command -v sort > /dev/null 2>&1 ; then
+	echo "Binary 'sort' not found but required."
+	exit 1
+fi
+
+if ! command -v uniq > /dev/null 2>&1 ; then
+	echo "Binary 'uniq' not found but required."
+	exit 1
+fi
+
 #
 # Paths
 #
@@ -121,7 +131,7 @@ fi
 # Check if there is at least one certificate available
 #
 SSL_DIRECTIVES="$( $(which find) "${NGINX_CONF_PATH}" -name "*.conf" -exec grep -E '[[:space:]]*ssl_certificate[[:space:]]+' "{}" \; )"
-CERTIFICATES="$( echo "${SSL_DIRECTIVES}" | awk '{print $2}' | awk -F ';' '{print $1}' )"
+CERTIFICATES="$( echo "${SSL_DIRECTIVES}" | awk '{print $2}' | awk -F ';' '{print $1}' | sort | uniq )"
 
 if [ "${SSL_DIRECTIVES}" = "" ]; then
 	echo "No SSL directives in nginx config files found"
@@ -151,9 +161,11 @@ watch_nginx_certs()
 	sendmail_bin="$( which sendmail )"
 
 	for c in ${CERTIFICATES}; do
-		# Check whether a warning message is needed, then issue one if so.
-		${certwatch_bin} ${opts} -q "${c}" &&
-		${certwatch_bin} ${opts} "${c}" | ${sendmail_bin} -oem -oi -t 2>/dev/null
+		if [ -f "${c}" ]; then
+			# Check whether a warning message is needed, then issue one if so.
+			${certwatch_bin} ${opts} -q "${c}" &&
+			${certwatch_bin} ${opts} "${c}" | ${sendmail_bin} -oem -oi -t 2>/dev/null
+		fi
 	done
 }
 
